// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function SetTitle(arg1:string):Promise<void>;

export function ShowDialog(arg1:string):Promise<void>;
